# Generated by Django 4.0.3 on 2022-03-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
