# Generated by Django 4.0.3 on 2022-04-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_myteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isRegistered',
            field=models.BooleanField(default=False),
        ),
    ]
