# Generated by Django 4.0.3 on 2022-04-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_isregistered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='username',
        ),
    ]
