# Generated by Django 4.0.3 on 2022-04-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_name_customer_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='username',
            new_name='name',
        ),
    ]
