# Generated by Django 4.0.3 on 2022-04-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_username_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
