# Generated by Django 4.0.3 on 2022-05-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='studentName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='accounts.customer'),
        ),
    ]
